apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: devtest-crossplane
    - key: Owner
      value: Anudeep
    - key: Name
      value: crossplane-vpc
    instanceTenancy: default
  providerConfigRef:
    name: default

